// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlxQ_evLfwj--89VzK5sRKTbYF8QbZ2ro',
    appId: '1:811935153506:web:4fb7e96920d669bac5c03b',
    messagingSenderId: '811935153506',
    projectId: 'flutternapratica',
    authDomain: 'flutternapratica.firebaseapp.com',
    storageBucket: 'flutternapratica.appspot.com',
    measurementId: 'G-YWMYGWL5SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdioiZ5NUx3ZcMeGdI-JSt4GjCipu6ak4',
    appId: '1:811935153506:android:3866023299c0a93fc5c03b',
    messagingSenderId: '811935153506',
    projectId: 'flutternapratica',
    storageBucket: 'flutternapratica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vlwKFO_aVVwnEdXTgyJQoSGXsmJavUI',
    appId: '1:811935153506:ios:6b516d94ba2caf43c5c03b',
    messagingSenderId: '811935153506',
    projectId: 'flutternapratica',
    storageBucket: 'flutternapratica.appspot.com',
    iosClientId: '811935153506-pdr70f3mnjc0imd3kqt115kl4t1qrod1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9vlwKFO_aVVwnEdXTgyJQoSGXsmJavUI',
    appId: '1:811935153506:ios:6b516d94ba2caf43c5c03b',
    messagingSenderId: '811935153506',
    projectId: 'flutternapratica',
    storageBucket: 'flutternapratica.appspot.com',
    iosClientId: '811935153506-pdr70f3mnjc0imd3kqt115kl4t1qrod1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
